// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Converters;

namespace BitfinexApi
{

    public class OrderStatusResponse
    {

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("cid")]
        public long Cid { get; set; }

        [JsonProperty("cid_date")]
        public string CidDate { get; set; }

        [JsonProperty("gid")]
        public object Gid { get; set; }

        [JsonProperty("symbol")]
        [JsonConverter(typeof(StringEnumConverter))]
        public OrderSymbols Symbol { get; set; }

        [JsonProperty("exchange")]
        [JsonConverter(typeof(StringEnumConverter))]
        public OrderExchanges Exchange { get; set; }

        [JsonProperty("price")]
        public double Price { get; set; }

        /// <summary>
        /// The average price at which this order as been executed so far. 0 if the order has not been executed at all
        /// </summary>
        [JsonProperty("avg_execution_price")]
        public double AvgExecutionPrice { get; set; }

        [JsonProperty("side")]
        [JsonConverter(typeof(StringEnumConverter))]
        public OrderSides Side { get; set; }

        [JsonProperty("type")]
        [JsonConverter(typeof(StringEnumConverter))]
        public OrderTypes Type { get; set; }

        [JsonProperty("timestamp")]
        public string Timestamp { get; set; }

        [JsonProperty("is_live")]
        public bool IsLive { get; set; }

        [JsonProperty("is_cancelled")]
        public bool IsCancelled { get; set; }

        [JsonProperty("is_hidden")]
        public bool IsHidden { get; set; }

        [JsonProperty("oco_order")]
        public object OcoOrder { get; set; }

        [JsonProperty("was_forced")]
        public bool WasForced { get; set; }

        [JsonProperty("original_amount")]
        public double OriginalAmount { get; set; }

        [JsonProperty("remaining_amount")]
        public double RemainingAmount { get; set; }

        [JsonProperty("executed_amount")]
        public double ExecutedAmount { get; set; }

        [JsonProperty("src")]
        public string Src { get; set; }
    }

}
