// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BitfinexApi
{

    public class TradeVol30d
    {

        [JsonProperty("curr")]
        public string Curr { get; set; }

        [JsonProperty("vol")]
        public string Vol { get; set; }
    }

}
