// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Messages
{

    internal class PaymentForwardCallback
    {

        [JsonProperty("value")]
        public int Value { get; set; }

        [JsonProperty("input_address")]
        public string InputAddress { get; set; }

        [JsonProperty("destination")] 
        public string Destination { get; set; }

        [JsonProperty("input_transaction_hash")]
        public string InputTransactionHash { get; set; }

        [JsonProperty("transaction_hash")]
        public string TransactionHash { get; set; }
    }

}
