// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.CCSPrepay.Models
{

    public class CardDetailData
    {

        [JsonProperty("CardNumber")]
        public string CardNumber { get; set; }

        [JsonProperty("Expiry")]
        public string Expiry { get; set; }

        [JsonProperty("CVV")]
        public string CVV { get; set; }

        [JsonProperty("BillingAddress")]
        public string BillingAddress { get; set; }
    }

}
