// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.CCSPrepay.Models
{

    public class CardBalanceData
    {

        [JsonProperty("clientId")]
        public string ClientId { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("cardStatus")]
        public string CardStatus { get; set; }

        [JsonProperty("availableBalance")]
        public string AvailableBalance { get; set; }
    }

}
