// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.CCSPrepay.Models
{
    public class GetTokenResponseImpl : BaseResponseImpl
    {
        [JsonProperty("data")]
        public GetTokenData Data { get; set; }
    }

    public class GetTokenResponse : BaseResponse
    {
        [JsonProperty("response")]
        public GetTokenResponseImpl Response { get; set; }

        public override void EnsureSuccess()
        {
            EnsureSuccessImpl(Response);
        }
    }
}
