// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{

    public class AdditionalInfoFinancial
    {

        [JsonProperty("Result")]
        public string Result { get; set; }

        [JsonProperty("TransactionID")]
        public string TransactionID { get; set; }
    }

}
