// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{

    public class Document
    {

        [JsonProperty("TypeID")]
        public int TypeID { get; set; }

        [JsonProperty("FileType")]
        public string FileType { get; set; }

        [JsonProperty("Base64")]
        public string Base64 { get; set; }

        [JsonProperty("IDNumber")]
        public string IDNumber { get; set; }
    }

}
