// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{
    public class CardholderTableItem
    {
        [JsonProperty("CardHolderID")]
        public string CardHolderID { get; set; }

        [JsonProperty("FirstName")]
        public string FirstName { get; set; }

        [JsonProperty("MiddleName")]
        public string MiddleName { get; set; }

        [JsonProperty("LastName")]
        public string LastName { get; set; }

        [JsonProperty("FirstName2")]
        public string FirstName2 { get; set; }

        [JsonProperty("MiddleName2")]
        public string MiddleName2 { get; set; }

        [JsonProperty("LastName2")]
        public string LastName2 { get; set; }

        [JsonProperty("FirstName3")]
        public string FirstName3 { get; set; }

        [JsonProperty("MiddleName3")]
        public string MiddleName3 { get; set; }

        [JsonProperty("LastName3")]
        public string LastName3 { get; set; }

        [JsonProperty("ShipToFirstName")]
        public string ShipToFirstName { get; set; }

        [JsonProperty("ShipToMiddleName")]
        public string ShipToMiddleName { get; set; }

        [JsonProperty("ShipToLastName")]
        public string ShipToLastName { get; set; }

        [JsonProperty("DOB")]
        public string DOB { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("Address2")]
        public string Address2 { get; set; }

        [JsonProperty("Address3")]
        public string Address3 { get; set; }

        [JsonProperty("Address4")]
        public string Address4 { get; set; }

        [JsonProperty("Address5")]
        public string Address5 { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("PostalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("Country")]
        public string Country { get; set; }

        [JsonProperty("ResidentialPhone")]
        public string ResidentialPhone { get; set; }

        [JsonProperty("WorkPhone")]
        public string WorkPhone { get; set; }

        [JsonProperty("CellNumber")]
        public string CellNumber { get; set; }

        [JsonProperty("CellPhoneProvider")]
        public string CellPhoneProvider { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("Gender")]
        public string Gender { get; set; }

        [JsonProperty("MotherMaidenName")]
        public string MotherMaidenName { get; set; }

        [JsonProperty("SSN")]
        public string SSN { get; set; }

        [JsonProperty("DrivingLicenseNumber")]
        public string DrivingLicenseNumber { get; set; }

        [JsonProperty("DrivingLicenseState")]
        public string DrivingLicenseState { get; set; }

        [JsonProperty("ForeignID")]
        public string ForeignID { get; set; }

        [JsonProperty("ForeignIDType")]
        public string ForeignIDType { get; set; }

        [JsonProperty("ForeignCountryCode")]
        public string ForeignCountryCode { get; set; }

        [JsonProperty("BillingAddress1")]
        public string BillingAddress1 { get; set; }

        [JsonProperty("BillingAddress2")]
        public string BillingAddress2 { get; set; }

        [JsonProperty("BillingAddress3")]
        public string BillingAddress3 { get; set; }

        [JsonProperty("BillingAddress4")]
        public string BillingAddress4 { get; set; }

        [JsonProperty("BillingAddress5")]
        public string BillingAddress5 { get; set; }

        [JsonProperty("BillingCity")]
        public string BillingCity { get; set; }

        [JsonProperty("BillingState")]
        public string BillingState { get; set; }

        [JsonProperty("BillingCountry")]
        public string BillingCountry { get; set; }

        [JsonProperty("BillingZipOrPostalCode")]
        public string BillingZipOrPostalCode { get; set; }

        [JsonProperty("ShippingAddressOptionId")]
        public double ShippingAddressOptionId { get; set; }

        [JsonProperty("Relation")]
        public string Relation { get; set; }

        [JsonProperty("CitizenCountry")]
        public string CitizenCountry { get; set; }

        [JsonProperty("Occupation")]
        public string Occupation { get; set; }

        [JsonProperty("NameofEmployer")]
        public string NameofEmployer { get; set; }

        [JsonProperty("EmploymentStatus")]
        public string EmploymentStatus { get; set; }

        [JsonProperty("ApplicationStatus")]
        public int ApplicationStatus { get; set; }

        [JsonProperty("StatusDescription")]
        public string StatusDescription { get; set; }

        [JsonProperty("PlaceOfBirth")]
        public string PlaceOfBirth { get; set; }

        [JsonProperty("Nationality")]
        public string Nationality { get; set; }

        [JsonProperty("CivilStatus")]
        public string CivilStatus { get; set; }
    }

    public class GetCardholderProfileTableResult
    {

        [JsonProperty("CardholderTable")]
        public CardholderTableItem[] CardholderTable { get; set; }
    }

    public class GetCardholderProfileResponse : BaseResponse
    {

        [JsonProperty("AdditionalInfo")]
        public AdditionalInfo AdditionalInfo { get; set; }

        [JsonProperty("TableResult")]
        public GetCardholderProfileTableResult TableResult { get; set; }
    }

}
