// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{

    public class GetExchangeRateTableItem
    {

        [JsonProperty("CurrencyFrom")]
        public string CurrencyFrom { get; set; }

        [JsonProperty("CurrencyTo")]
        public string CurrencyTo { get; set; }

        [JsonProperty("ExchangeRate")]
        public double ExchangeRate { get; set; }

        [JsonProperty("AmountFrom")]
        public double AmountFrom { get; set; }

        [JsonProperty("AmountTo")]
        public double AmountTo { get; set; }
    }

    public class GetExchangeRateTableResult
    {

        [JsonProperty("ExchangeRateTable")]
        public GetExchangeRateTableItem[] ExchangeRateTable { get; set; }
    }

    public class GetExchangeRateResponse : BaseResponse
    {
        [JsonProperty("AdditionalInfo")]
        public AdditionalInfo AdditionalInfo { get; set; }

        [JsonProperty("TableResult")]
        public GetExchangeRateTableResult TableResult { get; set; }
    }

}
