// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{

    public class GetExchangeRateRequest : BaseRequest
    {
        [JsonProperty("FromCurrency")]
        public string FromCurrency { get; set; }

        [JsonProperty("ToCurrency")]
        public string ToCurrency { get; set; }

        [JsonProperty("Amount")]
        public string Amount { get; set; }
    }

}
