// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{
    /*
        FL First Load First Load
        CD Batch Cr C2C Batch Credit Funds Transfer
        CD Batch Db C2C Batch Debit Funds Transfer
        T4 Reversal Reverse Transaction
        40 Card to Card Card to Card Transfer(Share Funds)
        00 Purchase Trans POS Purchase
        01 Withdraw Cash Cash Withdrawal
        MA Account Maint Account Maintenance
    */

    public class GetMiniStatementTableItem
    {
        [JsonProperty("TransactionID")]
        public string TransactionID { get; set; }

        [JsonProperty("TraceNumber")]
        public object TraceNumber { get; set; }

        [JsonProperty("TransactionTypeID")]
        public string TransactionTypeID { get; set; }

        [JsonProperty("TransactionDate")]
        public string TransactionDate { get; set; }

        [JsonProperty("Amount")]
        public double Amount { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }
    }

    public class GetMiniStatementTableResult
    {
        [JsonProperty("TransactionTable")]
        public TransactionTableItem[] TransactionTable { get; set; }
    }

    public class GetMiniStatementResponse : BaseResponse
    {
        [JsonProperty("AdditionalInfo")]
        public AdditionalInfo AdditionalInfo { get; set; }

        [JsonProperty("TableResult")]
        public GetMiniStatementTableResult TableResult { get; set; }
    }
}
