// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{

    public class RegisterCardholderRequest : BaseRequest
    {
        [JsonProperty("Firstname")]
        public string Firstname { get; set; }

        [JsonProperty("Lastname")]
        public string Lastname { get; set; }

        [JsonProperty("DateOfBirth")]
        public string DateOfBirth { get; set; }

        /// <summary>
        /// Required!
        /// </summary>
        [JsonProperty("Nationality")]
        public string Nationality { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("PostalCode")]
        public string PostalCode { get; set; }
        
        /// <summary>
        /// ISO3
        /// </summary>
        [JsonProperty("Country")]
        public string Country { get; set; }

        /// <summary>
        /// Required
        /// </summary>
        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("Documents")]
        public Document[] Documents { get; set; }

        [JsonProperty("CardReferenceID")]
        public string CardReferenceID { get; set; }

        [JsonProperty("Middlename")]
        public string Middlename { get; set; }

        [JsonProperty("Firstname2")]
        public string Firstname2 { get; set; }

        [JsonProperty("Middlename2")]
        public string Middlename2 { get; set; }

        [JsonProperty("Lastname2")]
        public string Lastname2 { get; set; }

        [JsonProperty("Firstname3")]
        public string Firstname3 { get; set; }

        [JsonProperty("Middlename3")]
        public string Middlename3 { get; set; }

        [JsonProperty("Lastname3")]
        public string Lastname3 { get; set; }

        [JsonProperty("ShipToFirstname")]
        public string ShipToFirstname { get; set; }

        [JsonProperty("ShipToMiddlename")]
        public string ShipToMiddlename { get; set; }

        [JsonProperty("ShipToLastname")]
        public string ShipToLastname { get; set; }

        [JsonProperty("PlaceOfBirth")]
        public string PlaceOfBirth { get; set; }

        [JsonProperty("CivilStatus")]
        public string CivilStatus { get; set; }

        [JsonProperty("Address2")]
        public string Address2 { get; set; }

        [JsonProperty("Address3")]
        public string Address3 { get; set; }

        [JsonProperty("Address4")]
        public string Address4 { get; set; }

        [JsonProperty("Address5")]
        public string Address5 { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("ResidentialPhone")]
        public string ResidentialPhone { get; set; }

        [JsonProperty("WorkPhone")]
        public string WorkPhone { get; set; }

        [JsonProperty("CellNumber")]
        public string CellNumber { get; set; }

        [JsonProperty("CellPhoneProvider")]
        public string CellPhoneProvider { get; set; }

        [JsonProperty("Gender")]
        public string Gender { get; set; }

        [JsonProperty("MotherMaidenName")]
        public string MotherMaidenName { get; set; }

        [JsonProperty("SSN")]
        public string SSN { get; set; }

        [JsonProperty("DrivingLicenseNumber")]
        public string DrivingLicenseNumber { get; set; }

        [JsonProperty("DrivingLicenseState")]
        public string DrivingLicenseState { get; set; }

        [JsonProperty("ForeignId")]
        public string ForeignId { get; set; }

        [JsonProperty("ForeignIdType")]
        public string ForeignIdType { get; set; }

        [JsonProperty("ForeignIdCounteryCode")]
        public string ForeignIdCounteryCode { get; set; }

        [JsonProperty("BillingAddress1")]
        public string BillingAddress1 { get; set; }

        [JsonProperty("BillingAddress2")]
        public string BillingAddress2 { get; set; }

        [JsonProperty("BillingAddress3")]
        public string BillingAddress3 { get; set; }

        [JsonProperty("BillingAddress4")]
        public string BillingAddress4 { get; set; }

        [JsonProperty("BillingAddress5")]
        public string BillingAddress5 { get; set; }

        [JsonProperty("BillingCity")]
        public string BillingCity { get; set; }

        [JsonProperty("BillingState")]
        public string BillingState { get; set; }

        [JsonProperty("BillingCountry")]
        public string BillingCountry { get; set; }

        [JsonProperty("BillingZipOrPostalCode")]
        public string BillingZipOrPostalCode { get; set; }

        [JsonProperty("ShippingAddressOptionId")]
        public string ShippingAddressOptionId { get; set; }

        [JsonProperty("Relation")]
        public string Relation { get; set; }

        [JsonProperty("CitizenCountry")]
        public string CitizenCountry { get; set; }

        [JsonProperty("Occupation")]
        public string Occupation { get; set; }

        [JsonProperty("NameOfEmployer")]
        public string NameOfEmployer { get; set; }

        [JsonProperty("EmploymentStatus")]
        public string EmploymentStatus { get; set; }
    }

}
