// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{
    public class CardHolderDetailsTableItem
    {

        [JsonProperty("CardHolderID")]
        public string CardHolderID { get; set; }

        [JsonProperty("FirstName")]
        public string FirstName { get; set; }

        [JsonProperty("MiddleName")]
        public object MiddleName { get; set; }

        [JsonProperty("LastName")]
        public string LastName { get; set; }

        [JsonProperty("FirstName2")]
        public object FirstName2 { get; set; }

        [JsonProperty("MiddleName2")]
        public object MiddleName2 { get; set; }

        [JsonProperty("LastName2")]
        public object LastName2 { get; set; }

        [JsonProperty("FirstName3")]
        public object FirstName3 { get; set; }

        [JsonProperty("MiddleName3")]
        public object MiddleName3 { get; set; }

        [JsonProperty("LastName3")]
        public object LastName3 { get; set; }

        [JsonProperty("ShipToFirstName")]
        public object ShipToFirstName { get; set; }

        [JsonProperty("ShipToMiddleName")]
        public object ShipToMiddleName { get; set; }

        [JsonProperty("ShipToLastName")]
        public object ShipToLastName { get; set; }

        [JsonProperty("DOB")]
        public string DOB { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("Address2")]
        public object Address2 { get; set; }

        [JsonProperty("Address3")]
        public object Address3 { get; set; }

        [JsonProperty("Address4")]
        public object Address4 { get; set; }

        [JsonProperty("Address5")]
        public object Address5 { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("State")]
        public object State { get; set; }

        [JsonProperty("PostalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("Country")]
        public string Country { get; set; }

        [JsonProperty("ResidentialPhone")]
        public object ResidentialPhone { get; set; }

        [JsonProperty("WorkPhone")]
        public object WorkPhone { get; set; }

        [JsonProperty("CellNumber")]
        public object CellNumber { get; set; }

        [JsonProperty("CellPhoneProvider")]
        public object CellPhoneProvider { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("Gender")]
        public object Gender { get; set; }

        [JsonProperty("MotherMaidenName")]
        public object MotherMaidenName { get; set; }

        [JsonProperty("SSN")]
        public string SSN { get; set; }

        [JsonProperty("DrivingLicenseNumber")]
        public object DrivingLicenseNumber { get; set; }

        [JsonProperty("DrivingLicenseState")]
        public object DrivingLicenseState { get; set; }

        [JsonProperty("ForeignID")]
        public object ForeignID { get; set; }

        [JsonProperty("ForeignIDType")]
        public object ForeignIDType { get; set; }

        [JsonProperty("ForeignCountryCode")]
        public object ForeignCountryCode { get; set; }

        [JsonProperty("BillingAddress1")]
        public object BillingAddress1 { get; set; }

        [JsonProperty("BillingAddress2")]
        public object BillingAddress2 { get; set; }

        [JsonProperty("BillingAddress3")]
        public object BillingAddress3 { get; set; }

        [JsonProperty("BillingAddress4")]
        public object BillingAddress4 { get; set; }

        [JsonProperty("BillingAddress5")]
        public object BillingAddress5 { get; set; }

        [JsonProperty("BillingCity")]
        public object BillingCity { get; set; }

        [JsonProperty("BillingState")]
        public object BillingState { get; set; }

        [JsonProperty("BillingCountry")]
        public object BillingCountry { get; set; }

        [JsonProperty("BillingZipOrPostalCode")]
        public object BillingZipOrPostalCode { get; set; }

        [JsonProperty("ShippingAddressOptionId")]
        public double ShippingAddressOptionId { get; set; }

        [JsonProperty("Relation")]
        public object Relation { get; set; }

        [JsonProperty("CitizenCountry")]
        public object CitizenCountry { get; set; }

        [JsonProperty("Occupation")]
        public object Occupation { get; set; }

        [JsonProperty("NameofEmployer")]
        public object NameofEmployer { get; set; }

        [JsonProperty("EmploymentStatus")]
        public object EmploymentStatus { get; set; }

        [JsonProperty("ApplicationStatus")]
        public int ApplicationStatus { get; set; }

        [JsonProperty("PlaceOfBirth")]
        public object PlaceOfBirth { get; set; }

        [JsonProperty("Nationality")]
        public string Nationality { get; set; }

        [JsonProperty("CivilStatus")]
        public object CivilStatus { get; set; }
    }

    public class CardDetailsTableItem
    {

        [JsonProperty("StartingNumbers")]
        public double StartingNumbers { get; set; }

        [JsonProperty("CardProgramCode")]
        public string CardProgramCode { get; set; }

        [JsonProperty("CustomerId")]
        public object CustomerId { get; set; }

        [JsonProperty("PrimaryCardNo")]
        public object PrimaryCardNo { get; set; }

        [JsonProperty("PrimaryCardReferenceID")]
        public object PrimaryCardReferenceID { get; set; }

        [JsonProperty("ExistingCardNo")]
        public object ExistingCardNo { get; set; }

        [JsonProperty("ExistingCardReferenceID")]
        public object ExistingCardReferenceID { get; set; }

        [JsonProperty("IsExternalCard")]
        public object IsExternalCard { get; set; }

        [JsonProperty("CardNo")]
        public string CardNo { get; set; }

        [JsonProperty("EncryptedCardNumber")]
        public string EncryptedCardNumber { get; set; }

        [JsonProperty("CardReferenceID")]
        public string CardReferenceID { get; set; }

        [JsonProperty("CardDesignID")]
        public object CardDesignID { get; set; }

        [JsonProperty("CardLogoID")]
        public object CardLogoID { get; set; }

        [JsonProperty("CardShippingMethodID")]
        public object CardShippingMethodID { get; set; }

        [JsonProperty("CardType")]
        public object CardType { get; set; }

        [JsonProperty("CardLinkType")]
        public object CardLinkType { get; set; }

        [JsonProperty("FulfillmentHouse")]
        public object FulfillmentHouse { get; set; }

        [JsonProperty("ExtraEmbossingLine")]
        public object ExtraEmbossingLine { get; set; }

        [JsonProperty("MemberNumber")]
        public object MemberNumber { get; set; }

        [JsonProperty("MemberType")]
        public object MemberType { get; set; }

        [JsonProperty("EmployerId")]
        public object EmployerId { get; set; }

        [JsonProperty("StakeholderId")]
        public object StakeholderId { get; set; }

        [JsonProperty("ExpiryDate")]
        public string ExpiryDate { get; set; }

        [JsonProperty("AAC")]
        public object AAC { get; set; }

        [JsonProperty("SecurityCode")]
        public object SecurityCode { get; set; }

        [JsonProperty("Citizen")]
        public object Citizen { get; set; }

        [JsonProperty("ReferalSource")]
        public object ReferalSource { get; set; }

        [JsonProperty("DeliveryMethod")]
        public object DeliveryMethod { get; set; }

        [JsonProperty("AcceptTermsDate")]
        public object AcceptTermsDate { get; set; }

        [JsonProperty("IsReadPrivacy")]
        public object IsReadPrivacy { get; set; }

        [JsonProperty("IsAcceptedAgreement")]
        public object IsAcceptedAgreement { get; set; }

        [JsonProperty("IsOptOptions")]
        public object IsOptOptions { get; set; }

        [JsonProperty("IPAddress")]
        public object IPAddress { get; set; }

        [JsonProperty("IsDupIPAddress")]
        public object IsDupIPAddress { get; set; }

        [JsonProperty("FreeText")]
        public object FreeText { get; set; }

        [JsonProperty("Reload1Company")]
        public object Reload1Company { get; set; }

        [JsonProperty("Reload1Address1")]
        public object Reload1Address1 { get; set; }

        [JsonProperty("Reload1Address2")]
        public object Reload1Address2 { get; set; }

        [JsonProperty("Reload1City")]
        public object Reload1City { get; set; }

        [JsonProperty("Reload1State")]
        public object Reload1State { get; set; }

        [JsonProperty("Reload1Zip")]
        public object Reload1Zip { get; set; }

        [JsonProperty("Reload1PhoneNo")]
        public object Reload1PhoneNo { get; set; }

        [JsonProperty("Reload1Ext")]
        public object Reload1Ext { get; set; }

        [JsonProperty("Reload1OpenAt")]
        public object Reload1OpenAt { get; set; }

        [JsonProperty("Reload1CloseAt")]
        public object Reload1CloseAt { get; set; }

        [JsonProperty("Reload1WeekOffDay")]
        public object Reload1WeekOffDay { get; set; }

        [JsonProperty("Reload1LoadFee")]
        public object Reload1LoadFee { get; set; }

        [JsonProperty("Reload2Company")]
        public object Reload2Company { get; set; }

        [JsonProperty("Reload2Address1")]
        public object Reload2Address1 { get; set; }

        [JsonProperty("Reload2Address2")]
        public object Reload2Address2 { get; set; }

        [JsonProperty("Reload2City")]
        public object Reload2City { get; set; }

        [JsonProperty("Reload2State")]
        public object Reload2State { get; set; }

        [JsonProperty("Reload2Zip")]
        public object Reload2Zip { get; set; }

        [JsonProperty("Reload2PhoneNo")]
        public object Reload2PhoneNo { get; set; }

        [JsonProperty("Reload2Ext")]
        public object Reload2Ext { get; set; }

        [JsonProperty("Reload2OpenAt")]
        public object Reload2OpenAt { get; set; }

        [JsonProperty("Reload2CloseAt")]
        public object Reload2CloseAt { get; set; }

        [JsonProperty("Reload2WeekOffDay")]
        public object Reload2WeekOffDay { get; set; }

        [JsonProperty("Reload2LoadFee")]
        public object Reload2LoadFee { get; set; }
    }

    public class SearchCustomerTableResult
    {

        [JsonProperty("CardHolderDetailsTable")]
        public CardHolderDetailsTableItem[] CardHolderDetailsTable { get; set; }

        [JsonProperty("CardDetailsTable")]
        public CardDetailsTableItem[] CardDetailsTable { get; set; }
    }

    public class SearchCustomerResponse : BaseResponse
    {

        [JsonProperty("AdditionalInfo")]
        public AdditionalInfo AdditionalInfo { get; set; }

        [JsonProperty("TableResult")]
        public SearchCustomerTableResult TableResult { get; set; }
    }

}
