// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{

    public class ShareFundsRequest : BaseRequest
    {
        [JsonProperty("FromCardReferenceID")]
        public string FromCardReferenceID { get; set; }

        [JsonProperty("ToCardReferenceID")]
        public string ToCardReferenceID { get; set; }

        [JsonProperty("Amount")]
        public string Amount { get; set; }
    }

}
