// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{
    public class UpdateProfileResponse : BaseResponse
    {
        [JsonProperty("AdditionalInfo")]
        public AdditionalInfo AdditionalInfo { get; set; }

        /// <summary>
        /// null returned; commenting out 
        /// </summary>
        //[JsonProperty("TableResult")]
        //public object TableResult { get; set; }
    }

}
