// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{
    //public class AdditionalInfoResetPIN
    //{
    //    [JsonProperty("ReturnStatus")]
    //    public string ReturnStatus { get; set; }

    //    [JsonProperty("NewPIN")]
    //    public string NewPIN { get; set; }
    //}

    public class ValidateCardPINResponse : BaseResponse
    {
        //[JsonProperty("AdditionalInfo")]
        //public AdditionalInfoResetPIN AdditionalInfo { get; set; }

        /// <summary>
        /// always null - commented out ---
        /// </summary>
        //[JsonProperty("TableResult")]
        //public object TableResult { get; set; }
    }

}
