// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Embily.Gateways.KoKard.Models
{

    public class VerifyCardTableItem
    {

        [JsonProperty("CardReferenceID")]
        public string CardReferenceID { get; set; }

        [JsonProperty("CardProgramID")]
        public string CardProgramID { get; set; }

        [JsonProperty("expDate")]
        public string ExpDate { get; set; }

        [JsonProperty("StatusCode")]
        public string StatusCode { get; set; }

        [JsonProperty("FirstName")]
        public string FirstName { get; set; }

        [JsonProperty("MiddleName")]
        public object MiddleName { get; set; }

        [JsonProperty("LastName")]
        public string LastName { get; set; }

        [JsonProperty("Address1")]
        public string Address1 { get; set; }

        [JsonProperty("Address2")]
        public object Address2 { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("State")]
        public object State { get; set; }

        [JsonProperty("PostalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("Country")]
        public string Country { get; set; }

        [JsonProperty("WorkPhone")]
        public object WorkPhone { get; set; }

        [JsonProperty("ResidentialPhone")]
        public object ResidentialPhone { get; set; }

        [JsonProperty("CellNumber")]
        public object CellNumber { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("Gender")]
        public object Gender { get; set; }

        [JsonProperty("Balance")]
        public double Balance { get; set; }

        [JsonProperty("MaxLoad")]
        public string MaxLoad { get; set; }

        [JsonProperty("MinLoad")]
        public string MinLoad { get; set; }
    }

    public class VerifyCardTableResult
    {

        [JsonProperty("VerifyCardTable")]
        public VerifyCardTableItem[] VerifyCardTable { get; set; }
    }

    public class VerifyCardResponse : BaseResponse
    {
        [JsonProperty("AdditionalInfo")]
        public AdditionalInfo AdditionalInfo { get; set; }

        [JsonProperty("TableResult")]
        public VerifyCardTableResult TableResult { get; set; }
    }

}
